sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: EsdBbgDqHZ7pPJgavB8QJYlWQ/MC6mRw0KK4WvNVXgzJl64AAJieTnT+cC+uDxZ3aZ2BsDX0YqjnDLThUoY0RrNXEdD1jMvSsMIsobz3CcczKXm0DpOd2okQbhjv6EgokfkCcmbp9BQTCf2I9xOfxNHYaEKkdipvWCS6y42sP5Q61ei0mTxc8PqebP9YyA6wWqbd2h7XRwJZFXczGTIOTSi0z6PPRb0Su8ThsZBN8wtN98dnuXOSDnwOki8GMaFJFQVM91tV/1V4PlIo/j4Q3rHYZJWmoPMY/sWjawnwdWC46gCw16EhGpFQ6BXPsylmQAeKc4pX98SV9UmesZ7zLS6vss8nKKgvF/2x2NB5Wy7hf2tmwW4TVJkUeJJR0938CfwFff9PkRndUAoNBC4J20+wQ7EG7n17gFUyyer5Qf/FDBVZI8nXlKwXP8180YLCEfuo+rXnLZxozUXVcfBgLaSg9jTQv3P2G4SLHmM/IITX7bpGZlYhbzNrVpvJNKZ5LWEsBmRzXCoGSc/4B8WzWS+7wGS/qB4bDv/mU2OhB/fsqbi7S8fhPh6y4e3btuAvXoarSTw7SGdOqqy/6CBuT6pcN9fRSMfi+Ayh6gdGvQd89aaw9+REwwOC2e96Xe18AShIH1cSlA0XwdE9PynF/HZYwEtzM//ISR4aHRs37zc=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: SIG9i4rDY89dXbbRds0irT9Kl6ZnZ45SRBF3jdVmvL3lbRSYGMAsRsRyVBZNYth/wJWfGneX57FiiLpezewkRnglzffP1onBCSsCiuuM1cdO6VeZN1y8nLoj8OsjxF7EHMSTfKx0R8EZC6gdw5+FdbDPSUoZWdg5jbqT/YB9nLEYZbkpTZdgjrdZ3nN7UZ7kQ+i9el/7y7i6S1ddDODgH3FvEHrLzPfohqUJGz80ZPyNTnJ/Tkf2umJ6dLOYoS8AhLQv8uJHqmizj0WGrMCWukraZBx91IVvURgirbhanck2YYIavt9LYImSmy6LirjVeSV46+f8MWIh6OwZF9YWTPtzG/XrLwxIud3hCKaLFj/GalpueUfZiV38dMuEraELNYTpLb14SB5WdI/Jlvao08y95mgEGeCw8NGBllITjPsLcE30eAzgpeVgVND09wVSrWOCpgNmnUZm4ie++0I3dzggwTEs/0dYvF+MHbpA7o0XelF79yYv+4yA3YIViJ6O/96aENo1JOiOaVCF06DH86xUlZ/WEHfEgzSP8OOknog33crX3mo2DpTic04NWuZKr56L2VbT/0BrA7rlpe8ey1azvSySqzxV3pq5PnrBJxc7+sGh39oYY/3Aq1F5QEhwz0Zr3byaydIcHq8E6oG2RLzxHYCkWqQgH6XsfYKmFZQ=
